# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import recommend_pb2 as recommend__pb2


class RecommendServiceStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecommendCategoryIDs = channel.unary_unary(
                '/recommend.RecommendService/GetRecommendCategoryIDs',
                request_serializer=recommend__pb2.GetRecommendCategoryIDsRequest.SerializeToString,
                response_deserializer=recommend__pb2.GetRecommendCategoryIDsResponse.FromString,
                )
        self.GetRecommendProductIDs = channel.unary_unary(
                '/recommend.RecommendService/GetRecommendProductIDs',
                request_serializer=recommend__pb2.GetRecommendProductIDsRequest.SerializeToString,
                response_deserializer=recommend__pb2.GetRecommendProductIDsResponse.FromString,
                )


class RecommendServiceServicer(object):
    """The greeting service definition.
    """

    def GetRecommendCategoryIDs(self, request, context):
        """get category recommend
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecommendProductIDs(self, request, context):
        """get product recommend
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecommendCategoryIDs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendCategoryIDs,
                    request_deserializer=recommend__pb2.GetRecommendCategoryIDsRequest.FromString,
                    response_serializer=recommend__pb2.GetRecommendCategoryIDsResponse.SerializeToString,
            ),
            'GetRecommendProductIDs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendProductIDs,
                    request_deserializer=recommend__pb2.GetRecommendProductIDsRequest.FromString,
                    response_serializer=recommend__pb2.GetRecommendProductIDsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommend.RecommendService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecommendService(object):
    """The greeting service definition.
    """

    @staticmethod
    def GetRecommendCategoryIDs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recommend.RecommendService/GetRecommendCategoryIDs',
            recommend__pb2.GetRecommendCategoryIDsRequest.SerializeToString,
            recommend__pb2.GetRecommendCategoryIDsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRecommendProductIDs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recommend.RecommendService/GetRecommendProductIDs',
            recommend__pb2.GetRecommendProductIDsRequest.SerializeToString,
            recommend__pb2.GetRecommendProductIDsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
